#ifndef __SKUNKEVENTSTATE__H__
#define __SKUNKEVENTSTATE__H__

#include <cstdint>

enum class SkunkEventState : uint32_t {
	ZONE_STATE_NO_INFO = 0,
	ZONE_STATE_NO_INVASION = 1,
	ZONE_STATE_TRANSITION = 2,
	ZONE_STATE_HIGH_ALERT = 3,
	ZONE_STATE_MEDIUM_ALERT = 4,
	ZONE_STATE_LOW_ALERT = 5,
	ZONE_STATE_DONE_TRANSITION = 6
};

#endif  //!__SKUNKEVENTSTATE__H__
